# This is a basic workflow that is manually triggered

name: Manual workflow - Boolean

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      # Maximum of 10 inputs
      root:
        type: boolean
        default: true
      en_US:
        type: boolean
      en_GB:
        type: boolean
      ar_AE:
        type: boolean
      de_DE:
        type: boolean
      es_ES:
        type: boolean
      fr_FR:
        type: boolean
      it_IT:
        type: boolean
      ja_JP:
        type: boolean

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Output selected locale
      run: echo "Building locales - ${{ github.event.inputs.locale }}"
